# Tugas Kelompok Modul 2
Nama Anggota Kelompok 8:

Arafi Ramadhan Maulana - 122450004
Dwi Ratna Anggraeni - 122450008
Raid Muhammad Naufal - 122450027
Rayan Koemi Karuby - 122450038
M. Deriansyah Okutra - 122450101

# Aplikasi Normalisasi Data

## Import Library

In [1]:
import numpy as np
import pandas as pd

## Import Dataset
https://drive.google.com/file/d/1IRgfUGlkIlZRFWQ5w3m5TbeFX6s_QidJ/view?usp=sharing

In [2]:
data = pd.read_csv("/content/Indonesia.csv")

## Dataset

In [3]:
data

    TAHUN    INFLASI        GDP
0    1980  18.035430  10.000000
1    1981  12.265909   7.878788
2    1982   9.445424   2.247191
3    1983  11.799741   4.395604
4    1984  10.455035   6.842105
5    1985   4.724536   2.463054
6    1986   5.822667   5.769231
7    1987   9.278656   5.000000
8    1988   8.045367   5.627706
9    1989   6.415540   7.786885
10   1990   7.819191   7.224335
11   1991   9.419058   6.775817
12   1992   7.523517   6.497507
13   1993   9.671893   6.496408
14   1994   8.532005   7.539971
15   1995   9.420323   8.220007
16   1996   7.973281   7.818187
17   1997   6.226142   4.699879
18   1998  58.451044 -13.126725
19   1999  20.477831   0.791126
20   2000   3.688619   4.920068
21   2001  11.500115   3.643466
22   2002  11.900118   4.499475
23   2003   6.757317   4.780369
24   2004   6.064060   5.030874
25   2005  10.453198   5.692571
26   2006  13.108672   5.500952
27   2007   6.406563   6.345022
28   2008  10.226665   6.013704
29   2009   4.386416   4.628871
30   2010   5.134204   6.223854
31   2011   5.356048   6.169784
32   2012   4.279500   6.030051
33   2013   6.412513   5.557264
34   2014   6.394925   5.006668
35   2015   6.363121   4.876322
36   2016   3.525805   5.033069
37   2017   3.808798   5.069786
38   2018   3.198346   5.174292
39   2019   3.030587   5.019288
40   2020   1.920968  -2.065512
41   2021   1.560130   3.703055
42   2022   4.209464   5.308595

### Statistika Deskriptif

In [4]:
data.describe()

             TAHUN    INFLASI        GDP
count    43.000000  43.000000  43.000000
mean   2001.000000   8.871831   4.956022
std      12.556539   8.672454   3.468557
min    1980.000000   1.560130 -13.126725
25%    1990.500000   4.929370   4.740124
50%    2001.000000   6.757317   5.308595
75%    2011.500000   9.949279   6.420715
max    2022.000000  58.451044  10.000000

## Kolom Data Normalisasi

In [5]:
kolom_dipilih = data[["INFLASI", "GDP"]]
kolom_dipilih

      INFLASI        GDP
0   18.035430  10.000000
1   12.265909   7.878788
2    9.445424   2.247191
3   11.799741   4.395604
4   10.455035   6.842105
5    4.724536   2.463054
6    5.822667   5.769231
7    9.278656   5.000000
8    8.045367   5.627706
9    6.415540   7.786885
10   7.819191   7.224335
11   9.419058   6.775817
12   7.523517   6.497507
13   9.671893   6.496408
14   8.532005   7.539971
15   9.420323   8.220007
16   7.973281   7.818187
17   6.226142   4.699879
18  58.451044 -13.126725
19  20.477831   0.791126
20   3.688619   4.920068
21  11.500115   3.643466
22  11.900118   4.499475
23   6.757317   4.780369
24   6.064060   5.030874
25  10.453198   5.692571
26  13.108672   5.500952
27   6.406563   6.345022
28  10.226665   6.013704
29   4.386416   4.628871
30   5.134204   6.223854
31   5.356048   6.169784
32   4.279500   6.030051
33   6.412513   5.557264
34   6.394925   5.006668
35   6.363121   4.876322
36   3.525805   5.033069
37   3.808798   5.069786
38   3.198346   5.174292
39   3.030587   5.019288
40   1.920968  -2.065512
41   1.560130   3.703055
42   4.209464   5.308595

## Normalisasi Data
Normlisasi data yang dilakukan dengan menggunakan metode skala desimal dan kemudian menambahkan ke dalam dataset.

In [6]:
def normalisasi_desimal(data, kolom, skala=2):
  pangkat = int(np.floor(np.log10(np.abs(np.max(data[kolom]))))) - skala + 1
  pangkat = min(pangkat, 0)
  divisor = 10**(-pangkat)
  normalisasi = lambda x: np.around(x / divisor, decimals=skala)

  data[f"{kolom}_Normalisasi"] = list(map(normalisasi, data[kolom]))
  return data

for kolom in kolom_dipilih:
  data = normalisasi_desimal(data, kolom)
data

    TAHUN    INFLASI        GDP  INFLASI_Normalisasi  GDP_Normalisasi
0    1980  18.035430  10.000000                18.04            10.00
1    1981  12.265909   7.878788                12.27             7.88
2    1982   9.445424   2.247191                 9.45             2.25
3    1983  11.799741   4.395604                11.80             4.40
4    1984  10.455035   6.842105                10.46             6.84
5    1985   4.724536   2.463054                 4.72             2.46
6    1986   5.822667   5.769231                 5.82             5.77
7    1987   9.278656   5.000000                 9.28             5.00
8    1988   8.045367   5.627706                 8.05             5.63
9    1989   6.415540   7.786885                 6.42             7.79
10   1990   7.819191   7.224335                 7.82             7.22
11   1991   9.419058   6.775817                 9.42             6.78
12   1992   7.523517   6.497507                 7.52             6.50
13   1993   9.671893   6.496408                 9.67             6.50
14   1994   8.532005   7.539971                 8.53             7.54
15   1995   9.420323   8.220007                 9.42             8.22
16   1996   7.973281   7.818187                 7.97             7.82
17   1997   6.226142   4.699879                 6.23             4.70
18   1998  58.451044 -13.126725                58.45           -13.13
19   1999  20.477831   0.791126                20.48             0.79
20   2000   3.688619   4.920068                 3.69             4.92
21   2001  11.500115   3.643466                11.50             3.64
22   2002  11.900118   4.499475                11.90             4.50
23   2003   6.757317   4.780369                 6.76             4.78
24   2004   6.064060   5.030874                 6.06             5.03
25   2005  10.453198   5.692571                10.45             5.69
26   2006  13.108672   5.500952                13.11             5.50
27   2007   6.406563   6.345022                 6.41             6.35
28   2008  10.226665   6.013704                10.23             6.01
29   2009   4.386416   4.628871                 4.39             4.63
30   2010   5.134204   6.223854                 5.13             6.22
31   2011   5.356048   6.169784                 5.36             6.17
32   2012   4.279500   6.030051                 4.28             6.03
33   2013   6.412513   5.557264                 6.41             5.56
34   2014   6.394925   5.006668                 6.39             5.01
35   2015   6.363121   4.876322                 6.36             4.88
36   2016   3.525805   5.033069                 3.53             5.03
37   2017   3.808798   5.069786                 3.81             5.07
38   2018   3.198346   5.174292                 3.20             5.17
39   2019   3.030587   5.019288                 3.03             5.02
40   2020   1.920968  -2.065512                 1.92            -2.07
41   2021   1.560130   3.703055                 1.56             3.70
42   2022   4.209464   5.308595                 4.21             5.31